//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace to_do_list.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tasks
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DATEOFTASK { get; set; }
        public Nullable<bool> STATUS { get; set; }
    }
}
